### ISSUE TITLE
Problem Set 6

### ISSUE THREAD

**Issue by DuKle3** [0130w/mit18.06#5]
Problem 3 : (1) rank of B should be 2
Problem 5 : rank of A should be 1
Problem 9 : eigenvalue of A2 should be 0.9 and 0.3 (雖然不影響那小題要問的)

**Comment by 0130w** [comment]
感谢指正，我已经检查并且修复了。
同时，如果您不介意的话，我希望能够将您@在README中的致谢名单中，以感谢您对这个仓库作出的帮助～

**Comment by 0130w** [comment]
@DuKle3 不好意思，习惯性把issue关闭了，可能不能回复这样

**Comment by DuKle3** [comment]
沒問題！
也感謝您讓我有寫題目的動力:D
